WITH ENUM AS (
    SELECT X, Y, ROW_NUMBER() OVER (ORDER BY X, Y) AS ROW_NUM
    FROM FUNCTIONS
)
SELECT DISTINCT E.X, E.Y
FROM ENUM E
JOIN ENUM E2 ON E.X = E2.Y AND E.Y = E2.X AND E.ROW_NUM <> E2.ROW_NUM
WHERE E.X <= E.Y
ORDER BY E.X, E.Y;