SELECT 
(CASE 
 WHEN STUDENTS.MARKS < 70 THEN NULL 
 ELSE STUDENTS.NAME 
 END) AS NAME, GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS 
JOIN GRADES 
ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK 
ORDER BY GRADES.GRADE DESC,NAME,STUDENTS.MARKS
;